# Generated by Django 6.0.4 on 2026-05-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='age',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.EmailField(default=18, max_length=254),
            preserve_default=False,
        ),
    ]
