# Generated by Django 6.0.4 on 2026-05-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0002_students_age_students_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
